# Generated by Django 3.1.3 on 2020-11-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201117_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
