# Generated by Django 3.1.3 on 2020-11-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201117_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='medium',
            field=models.CharField(choices=[('English', 'English'), ('Bangla', 'Bangla')], default='Bangla', max_length=50),
        ),
    ]
