# Generated by Django 3.1.3 on 2020-11-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201119_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='class_school',
            field=models.CharField(choices=[('TWELVE', '12'), ('ELEVEN', '11'), ('TEN', '10'), ('NINE', '9'), ('EIGHT', '8'), ('SEVEN', '7'), ('SIX', '6'), ('FIVE', '5'), ('FOUR', '4'), ('THREE', '3'), ('TWO', '2'), ('ONE', '1')], default='ONE', max_length=15),
        ),
    ]
